name: Deploy Production in Hostinger

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy-in-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.3"
      - name: Install npm dependencies
        run: npm install
      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Build con variable de entorno
        run: |
          if [ "${{ env.BRANCH_NAME }}" == "develop" ]; then
            echo "Ejecutando build con NODE_ENV=development"
            npm run build-dev
          else
            echo "Ejecutando build con NODE_ENV=production"
            npm run build-prod
          fi
        shell: bash
        env:
          BRANCH_NAME: ${{ github.ref_name }}
      - name: Configurar FTP
        run: |
          echo "${{ secrets.FTP_HOST }}" >> ftp_host.txt
          echo "${{ secrets.FTP_USERNAME }}" >> ftp_username.txt
          echo "${{ secrets.FTP_PASSWORD }}" >> ftp_password.txt
      - name: Deploy in Hostinger
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y lftp
          lftp -e "set ssl:verify-certificate no; open $(cat ftp_host.txt); user $(cat ftp_username.txt) $(cat ftp_password.txt); mirror -X .* -X .*/ --reverse --verbose dist/ ./${{ env.BRANCH_NAME }}/; bye"
